// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MediaFile struct {
	Name    pgtype.Text
	Fileoid pgtype.Uint32
}

type Medium struct {
	ID      int32
	Hash    string
	Title   string
	Creator string
}
